#pragma config(Motor,  port2,           leftwheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           forklift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           eeud,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           flappywing,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           Arm,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           eelr,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           rightwheel,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void drive(){
	motor[port2] = vexRT[Ch3];
	motor[port9] = vexRT[Ch2];

}

void collection() {
			if(vexRT[Btn5U] == 1)
   	{
		  motor[port3] = 100;
	  }
	  else if (vexRT[Btn5D] == 1)
	  {
		  motor[port3] = -100;
	  }
	  else
	  {
		  motor[port3] = 0;
	  }
}

void flappy_wing(){
		if(vexRT[Btn7R] == 1)
   	{
		  motor[port5] = 100;
	  }
	  else if (vexRT[Btn7L] == 1)
	  {
		  motor[port5] = -100;
	  }
	  else
	  {
		  motor[port5] = 0;
	  }

}
void arm() {
	if(vexRT[Btn6U] == 1)
   	{
		  motor[port6] = 100;
	  }
	  else if (vexRT[Btn6D] == 1)
	  {
		  motor[port6] = -100;
	  }
	  else
	  {
		  motor[port6] = 0;
	  }
}

void end_effector()
{
	if(vexRT[Btn8U] == 1)
	{
		motor[port4] = 100;
	}
	else if (vexRT[Btn8D] == 1)
{
	motor[port4]= -100;
}
else
{
	motor[port8] = 0;
}
	if(vexRT[Btn8R] == 1)
	{
		motor[port8] = 100;
	}
	else if (vexRT[Btn8L] == 1)
	{
		motor[port8]= -100;
}
else
{
motor[port8] = 0;
}
}

task main ()
{

	while (1)
	{

		drive();
		collection();
	  flappy_wing();
	  arm();
	  end_effector();

	}
}
